name: Benchmark with JMH
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install BMUtils
        run: mvn clean install
      - name: Compile benchmark
        run: mvn -f benchmark/pom.xml clean verify
      - name: Run benchmark
        run: java -jar benchmark/target/benchmarks.jar -wi 1 -i 1 -f 1 -rf json

      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: JMH Benchmark
          tool: 'jmh'
          output-file-path: jmh-result.json
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Set auto-push to false since GitHub API token is not given
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@TechnicJelle'
          gh-repository: 'github.com/TechnicJelle/BMUtils-PerformanceReports'
          gh-pages-branch: 'main'
          benchmark-data-dir-path: './'
