name: Deploy to BlueColored Repo

on:
  release:
    types: [ released ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up credentials
        shell: bash
        env:
          USERNAME: ${{ secrets.MAVEN_NAME }}
          PASSWORD: ${{ secrets.MAVEN_SECRET }}
        run: echo "<settings><servers><server><id>bluecolored-releases</id><username>$USERNAME</username><password>$PASSWORD</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Deploy
        run: mvn clean deploy
